# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1ff5ca26679209155b8d0fcf0ba57c5ed78ea30d96119cc9ab067cefe49c64f6edefee378d0e15d6668dfe951669f3b1b0a6a7d61c6f4110335800d978f513b

test:
  secret_key_base: ebf7e1dc160bb983fe0d888483f99aa4cd0a59161fbf9cf56f535d3ab8773d34607b55a1bc495c3f780025356ad48993508b2654f2dd317067bd4e3765fa22ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
